spring:
  application:
    name: beginning_of_stream

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

server:
  port: 8081
