server:
  port: 8080

spring:
  application:
    name: exclude_duplicate_producer

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

redis:
  stream:
    name: exclude_duplicate_producer_stream_json
    key: event
    max-length: 10


